### ISSUE TITLE
Modulo behaves incorrectly for differing Exp values

### ISSUE THREAD

**Issue by spiveeworks** [programble/fix#1]
The signature of `impl Rem for Fix` suggests that the two operands can have different Exp values, but their implementation is only correct if they have the same Exp value.

For example:
`assert_eq!(Megi::new(2) % Kibi::new(2047), 1)`
This should evaluate `2048Ki % 2047Ki` and get 1Ki, or at least `2Mi % 1Mi` and get 0Mi, but it currently evaluates `2 % 2047` and gets 2.

**Comment by spiveeworks** [comment]
Of course just restricting the impl to equal Exp's avoids an implicit conversion, which seems like a design goal here?

**Comment by causal-agent** [comment]
Oops, didn't think that one through properly.
